name: active-mq-service
services:
  activemq:
    image: rmohr/activemq:5.15.9
    container_name: active-mq
    environment:
      ACTIVEMQ_ADMIN_LOGIN: admin
      ACTIVEMQ_ADMIN_PASSWORD: admin

      ACTIVEMQ_OPTS: "-Xms512M -Xmx1G"

      ACTIVEMQ_CONFIG_MINMEMORY: 512
      ACTIVEMQ_CONFIG_MAXMEMORY: 1024

    ports:
      # ui
      - "8161:8161"
      # jms
      - "61616:61616"

    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8161"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

    restart: unless-stopped

    deploy:
      resources:
        limits:
          memory: 1GB
        reservations:
          memory: 512M