name: active-mq-service
services:
  activemq:
    image: apache/activemq-artemis:latest
    container_name: active-mq
    environment:
      ARTEMIS_USER: admin
      ARTEMIS_PASSWORD: admin
      JAVA_OPTS: "-Xms512M -Xmx1G"

    ports:
      # Web console
      - "8161:8161"
      # JMS port
      - "61616:61616"

    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:8161" ]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

    restart: unless-stopped

    deploy:
      resources:
        limits:
          memory: 1GB
        reservations:
          memory: 512M